from pathlib import Path
p = Path(__file__).with_name("main.tex"); s = p.read_text(encoding="utf-8")
R = [
(r"\quad LOPO on translations, range & \TrGoogleMin{}--\TrGoogleMax{} & \TrLLMMin{}--\TrLLMMax{} \\" + "\n", ""),
(r"\quad Model $\eta^2$, before $\to$ after & \TrGoogleEtaBefore{} $\to$ \TrGoogleEtaAfter{} & \TrLLMEtaBefore{} $\to$ \TrLLMEtaAfter{} \\" + "\n", ""),
(r"Second, languages differ in script and morphology, so many classic stylometric measures (readability formulas, contractions, hedge lists) are undefined outside English, and the measures that are defined may track the language more than the author.", r"Second, languages differ in script and morphology, so many classic stylometric measures (readability formulas, contractions, hedge lists) are undefined outside English."),
(r"Our contributions are: (i) a content-controlled multilingual corpus of \NCollected{} essays (5 models $\times$ 7 languages $\times$ 12 prompts $\times$ 2 generations) and \NTranslations{} machine translations, released with code; (ii) a \NFeatures{}-feature representation with one definition in every language, with which five-way attribution reaches \LRmin{}--\LRmax{} in all seven languages, with no detectable resource gradient and with five features carrying most of the signal; (iii) a direct comparison with character $n$-grams showing that the opaque baseline is more accurate within a language but that only the interpretable features carry a classifier across a language or translation boundary without retraining; (iv) evidence that models converge stylistically in lower-resource languages while remaining attributable, and that LLM judges attribute at or near chance.", r"Our contributions are: (i) a content-controlled corpus of \NCollected{} essays (5 models $\times$ 7 languages $\times$ 12 prompts $\times$ 2 generations) and \NTranslations{} machine translations, released with code; (ii) a \NFeatures{}-feature representation with one definition in every language, reaching \LRmin{}--\LRmax{} five-way accuracy in all seven languages with no detectable resource gradient; (iii) a comparison with character $n$-grams showing that the opaque baseline is more accurate within a language but only the interpretable features carry a classifier across a language or translation boundary without retraining; (iv) evidence that models converge stylistically in lower-resource languages while remaining attributable, and that LLM judges attribute near chance."),
(r"Per-model recall is highest for GPT-5.5 (\RecallgptMin{}--\RecallgptMax{} across languages) and Grok 4.3 (\RecallgrokMin{}--\RecallgrokMax{}), then Claude Opus 4.7 (\RecallclaudeMin{}--\RecallclaudeMax{}) and Gemini 3.5 Flash (\RecallgeminiMin{}--\RecallgeminiMax{}); DeepSeek V4 Pro is hardest (\RecalldeepseekMin{}--\RecalldeepseekMax{}).", r"Per-model recall is highest for GPT-5.5 (\RecallgptMin{}--\RecallgptMax{}) and Grok 4.3 (\RecallgrokMin{}--\RecallgrokMax{}); DeepSeek V4 Pro is hardest (\RecalldeepseekMin{}--\RecalldeepseekMax{})."),
(r"Each prompt was sent as a single user turn with no system prompt at temperature 0.7, twice per cell with fixed seeds and reasoning traces excluded, giving $5 \times 12 \times 7 \times 2 = \NCollected{}$ responses. Each passed language identification (confidence $\geq 0.6$), a 150--900 word-equivalent window and a per-language refusal check.", r"Each prompt was sent as a single user turn, no system prompt, temperature 0.7, twice per cell with fixed seeds and reasoning traces excluded: $5 \times 12 \times 7 \times 2 = \NCollected{}$ responses, each passing language identification, a 150--900 word-equivalent window and a refusal check."),
(r"The unit of analysis is one response. The two generations of a prompt are not independent, so every cross-validation split is leave-one-prompt-out (LOPO, 12 folds) and every confidence interval and clustered standard error groups by prompt.", r"The unit of analysis is one response; the two generations of a prompt are not independent, so every split is leave-one-prompt-out (LOPO, 12 folds) and every interval and clustered standard error groups by prompt."),
(r"A classifier trained on the English originals reads the translations at \TrGoogleTrainEn{} (Google) and \TrLLMTrainEn{} (LLM), while one trained on the models' own native responses in the target language reads them at only \TrGoogleTrainNative{}--\TrLLMTrainNative{}: translated GPT-5.5 text resembles English GPT-5.5 more than native Spanish GPT-5.5, because the translator carries over the source's structural habits.", r"A classifier trained on the English originals reads the translations at \TrGoogleTrainEn{} (Google) and \TrLLMTrainEn{} (LLM), one trained on native target-language responses at only \TrGoogleTrainNative{}--\TrLLMTrainNative{}: the translator carries over the source's structural habits."),
]
for a, b in R:
    assert a in s, "NOT FOUND: " + a[:70]
    s = s.replace(a, b)
p.write_text(s, encoding="utf-8"); print("trim2 applied")
