from pathlib import Path
p = Path(__file__).with_name("main.tex"); s = p.read_text(encoding="utf-8")
R = [
(r"Language dominates every feature tied to morphology or vocabulary (token length \EtaLangmeantokenlen{}, function-word ratio \EtaLangfuncwordratio{}, hapax rate \EtaLanghapaxrate{}, Zipf slope \EtaLangzipfslope{}, MATTR \EtaLangmattr{}). Model effects are largest for hapax rate (\EtaModelhapaxrate{}), Zipf slope (\EtaModelzipfslope{}), comma rate (\EtaModelcommaperbk{}), bigram entropy (\EtaModelbigramentropy{}) and paragraph count (\EtaModelparacount{}), and smallest for subordination, question rate and dependency depth ($\leq \EtaModelSmallMax{}$): the models differ in how varied their vocabulary is and how they punctuate and paragraph, not in clause structure.", r"Language dominates every feature tied to morphology or vocabulary (token length \EtaLangmeantokenlen{}, function-word ratio \EtaLangfuncwordratio{}, hapax rate \EtaLanghapaxrate{}). Model effects are largest for hapax rate (\EtaModelhapaxrate{}), Zipf slope (\EtaModelzipfslope{}), comma rate (\EtaModelcommaperbk{}) and paragraph count (\EtaModelparacount{}), and smallest for subordination, question rate and dependency depth ($\leq \EtaModelSmallMax{}$): the models differ in vocabulary variety, punctuation and paragraphing, not in clause structure."),
(r"Each judge defaults to one answer: GPT-5.5 names itself for \JudgegptSelfClaim{} of texts regardless of author, Claude most often names GPT-5.5, and the other three most often name Claude. The feature classifier exceeds the best judge by \GapJudgeMin{}--\GapJudgeMax{} points in every language, all Holm-corrected $p < 10^{-4}$. This is the single-text, instant-answer condition; the companion study shows that a side-by-side lineup with reasoning enabled raises the same judges, and Claude's self-recognition in particular, well above these figures~\cite{erlikhman2026compllm}.", r"Each judge defaults to one answer: GPT-5.5 names itself for \JudgegptSelfClaim{} of texts regardless of author, and the others mostly name Claude or GPT-5.5. The feature classifier exceeds the best judge by \GapJudgeMin{}--\GapJudgeMax{} points in every language (Holm-corrected $p < 10^{-4}$). This is the single-text, instant-answer condition; a side-by-side lineup with reasoning enabled raises the same judges, and Claude's self-recognition in particular, well above these figures~\cite{erlikhman2026compllm}."),
(r"\textbf{Limitations.} (i) One genre, persuasive essays with a three-claim structure; paragraph count partly reflects instruction following, and other genres may fingerprint differently. (ii) Length is entangled with style; the length-controlled result holds only non-linearly.", r"\textbf{Limitations.} (i) One genre, persuasive essays with a three-claim structure; paragraph count partly reflects instruction following. (ii) Length is entangled with style; the length-controlled result holds only non-linearly."),
(r"\textbf{Dual use.} The same pipeline can attribute text to a person, and the translation result suggests machine translation offers pseudonymous writers little protection against structural stylometry. We release only model-generated text and no tools aimed at human authors.", r"\textbf{Dual use.} The same pipeline can attribute text to a person, and machine translation offers pseudonymous writers little protection against structural stylometry. We release only model-generated text."),
(r"Stylometric detection has been applied language by language with language-specific feature sets, for Japanese~\cite{zaitsu2025stylometry} and Polish~\cite{przystalski2025stylometry} among others. UD-based features have been used for cross-language attribution of human authors~\cite{murauer2021dtgrams}.", r"Stylometric detection has been applied language by language with language-specific feature sets, e.g.\ Japanese~\cite{zaitsu2025stylometry} and Polish~\cite{przystalski2025stylometry}; UD-based features have been used for cross-language attribution of human authors~\cite{murauer2021dtgrams}."),
]
for a, b in R:
    assert a in s, "NOT FOUND: " + a[:70]
    s = s.replace(a, b)
p.write_text(s, encoding="utf-8"); print("trim3 applied")
