from pathlib import Path
p = Path(__file__).with_name("main.tex"); s = p.read_text(encoding="utf-8")
R = [
(r"were queried through OpenRouter in September 2026, with the served model identifier logged for every response.\footnote{\raggedright OpenRouter identifiers: \texttt{openai/gpt-5.5}, \texttt{google/gemini-3.5-flash}, \texttt{anthropic/claude-opus-4.7}, \texttt{x-ai/grok-4.3}, \texttt{deepseek/deepseek-v4-pro-0813}.}",
 r"were queried through OpenRouter in September 2026, with the served model identifier logged for every response (identifiers are listed in the repository)."),
(r"The ranking is contestable: Joshi et al.~\cite{joshi2020state} place English, Spanish, Chinese and Japanese in their highest class (5) and Russian, Turkish and Hindi one class lower (4), and corpus-based orderings disagree with each other, so we report the two-class split beside the pre-registered order.",
 r"The ranking is contestable: Joshi et al.~\cite{joshi2020state} place English, Spanish, Chinese and Japanese in their highest class (5) and Russian, Turkish and Hindi one lower (4), so we report that two-class split beside the pre-registered order."),
(r"\textbf{RQ5.} All 120 English responses were translated into the six other languages by Google Translate and by an open model that is not a subject (MiniMax M3); we measure model attribution on the translations alone, transfer from classifiers trained on the English originals or on native target-language responses (features z-scored within each set), and per-feature Spearman correlations between originals and translations.",
 r"\textbf{RQ5.} All 120 English responses were translated into the six other languages by Google Translate and by an open non-subject model (MiniMax M3); we measure attribution on the translations alone, transfer from classifiers trained on the English originals or on native target-language responses (features z-scored within each set), and per-feature Spearman correlations between originals and translations."),
(r"\textbf{RQ6.} Each subject model was asked, one text at a time with a shuffled candidate list and no metadata, which of the five models wrote it (temperature 0, hidden reasoning disabled where the API allows it), following the exact-model-prediction task of Bai et al.~\cite{bai2025selfrecognition}.",
 r"\textbf{RQ6.} Each subject model was asked, one text at a time with a shuffled candidate list and no metadata, which of the five wrote it (temperature 0, hidden reasoning off where the API allows), the exact-model-prediction task of Bai et al.~\cite{bai2025selfrecognition}."),
(r"\textbf{Limitations.} (i) One genre, persuasive essays with three fixed claims and no lists, so paragraph count and length partly record how each model lays out an argument under instruction; both translators also keep paragraph boundaries, so these features survive translation partly by construction. (ii) Length is entangled with style, and the transfer, convergence and translation analyses are not length-controlled.",
 r"\textbf{Limitations.} (i) One genre, persuasive essays with three fixed claims and no lists, so paragraph count and length partly record how each model lays out an argument, and both translators keep paragraph boundaries, so those features survive translation partly by construction. (ii) Length is entangled with style; the transfer, convergence and translation analyses are not length-controlled."),
(r"(iv) Eight of the \NFeatures{} features depend on Stanza parses or sentence splitting, and parser accuracy varies by language without following the resource order (Hindi and Russian are parsed most accurately, Turkish and Chinese least~\cite{qi2020stanza}); four of the five top pooled features are parser-free.",
 r"(iv) Eight of the \NFeatures{} features depend on Stanza parses or sentence splitting; parser accuracy varies by language without following the resource order (Hindi and Russian parse best, Turkish and Chinese worst~\cite{qi2020stanza}), and four of the five top pooled features are parser-free."),
(r"Interpretable authorship attribution does not require English: the three Class-4 languages average \ClassFourMean{} against \ClassFiveMean{} for the four Class-5 languages, a gap inside the $\pm$\ClusterCIhalfwidth{}-point intervals, and a classifier trained in one language transfers to the others after unlabelled standardization.",
 r"Interpretable authorship attribution does not require English: the three Class-4 languages average \ClassFourMean{} against \ClassFiveMean{} for the four Class-5 languages, inside the $\pm$\ClusterCIhalfwidth{}-point intervals, and a classifier trained in one language transfers to the others after unlabelled standardization."),
(r"Two caveats: the test language contains the \NPrompts{} training prompts, so off-diagonal cells are an upper bound for unseen prompts, and both representations use the test language's own unlabelled statistics.",
 r"Two caveats: the test language contains the \NPrompts{} training prompts, so off-diagonal cells are an upper bound for unseen prompts, and both representations use the test language's unlabelled statistics."),
(r"Bai et al.~\cite{bai2025selfrecognition} report the same near-chance, GPT- and Claude-biased behaviour in English; it holds in all seven languages here. A companion study shows that a side-by-side lineup with reasoning enabled raises the same judges~\cite{erlikhman2026compllm}.",
 r"Bai et al.~\cite{bai2025selfrecognition} report the same near-chance, GPT- and Claude-biased behaviour in English; it holds in all seven languages here, and a side-by-side lineup with reasoning enabled raises the same judges~\cite{erlikhman2026compllm}."),
]
for a, b in R:
    assert a in s, "NOT FOUND: " + a[:70]
    s = s.replace(a, b)
p.write_text(s, encoding="utf-8"); print("trim7 applied")
